log:
  dateFormat: "YYYY-MM-DD"
  datetimeFormat: "YYYY-MM-DD HH:mm:ss"
  jsonIndent: 2
cache:
  ttl: 300
  checkPeriod: 600
  useClones: false
express:
  requestSizeLimit: 50mb
users:
  technical:
    email: "technical@guirlande.com"
    name: "Technical user"
guirlande:
  codeLength: 4
  pins:
    red: 18
    green: 13
    blue: 19
